# Generated by Django 6.0.4 on 2026-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0003_alter_customuser_referral_code_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
