# Generated by Django 6.0.4 on 2026-05-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0004_transaction_api_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MTN', 'MTN'), ('Airtel', 'Airtel'), ('GLO', 'GLO'), ('9mobile', '9mobile')], max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Data_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=240)),
                ('Duration', models.CharField(max_length=240)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcard_app.network')),
            ],
        ),
    ]
