# Generated by Django 6.0.4 on 2026-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0005_network_data_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_price',
            name='size',
            field=models.CharField(default='0mb', max_length=240),
        ),
        migrations.AlterField(
            model_name='data_price',
            name='Duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
