# Generated by Django 6.0.4 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0006_data_price_size_alter_data_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_price',
            name='Duration',
            field=models.CharField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data_price',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
