# Generated by Django 6.0.4 on 2026-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0007_alter_data_price_duration_alter_data_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_price',
            name='price',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
