# Generated by Django 6.0.4 on 2026-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0008_alter_data_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_price',
            name='id_number',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
