# Generated by Django 6.0.4 on 2026-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0009_data_price_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_price',
            name='id_number',
        ),
        migrations.AddField(
            model_name='data_price',
            name='id_network',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
