# Generated by Django 6.0.4 on 2026-05-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0010_remove_data_price_id_number_data_price_id_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_price',
            old_name='id_network',
            new_name='networkid',
        ),
    ]
