# Generated by Django 6.0.4 on 2026-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0011_rename_id_network_data_price_networkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bvn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='flutterwave_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='virtual_account_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='virtual_account_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='virtual_account_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
