# Generated by Django 6.0.4 on 2026-05-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0012_profile_bvn_profile_flutterwave_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('auto_kyc', models.BooleanField(default=False)),
                ('fraud_detection', models.BooleanField(default=True)),
                ('min_airtime', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('max_airtime', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('daily_wallet_limit', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
            ],
        ),
    ]
