# Generated by Django 6.0.4 on 2026-05-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0013_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_price',
            name='referral_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
