# Generated by Django 6.0.4 on 2026-05-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0014_data_price_referral_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_dynamic_va',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_static_va',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DynamicVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('expiry_at', models.DateTimeField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
