# Generated by Django 6.0.4 on 2026-05-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0017_customuser_referral_wallet_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='flutterwave_customer_id',
            new_name='katpay_customer_id',
        ),
    ]
