# Generated by Django 6.0.4 on 2026-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0018_rename_flutterwave_customer_id_profile_katpay_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(choices=[('airtime', 'Airtime'), ('data', 'Data'), ('cable', 'Cable TV'), ('electricity', 'Electricity'), ('exam_pin', 'Exam Pin'), ('bulk_sms', 'Bulk SMS'), ('wallet_funding', 'Wallet Funding')], max_length=20),
        ),
    ]
