# Generated by Django 6.0.4 on 2026-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0019_alter_transaction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
