# Generated by Django 6.0.4 on 2026-05-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0020_customuser_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='transaction_pin',
        ),
    ]
