# Generated by Django 6.0.4 on 2026-05-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0022_customuser_transaction_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.CharField(max_length=255)),
                ('auth_header_key', models.CharField(default='Authorization', help_text='e.g. Authorization or api-key', max_length=100)),
                ('auth_header_value', models.CharField(help_text='e.g. Bearer Token_here or api_key_value', max_length=255)),
                ('additional_headers', models.TextField(blank=True, default='{}', help_text='JSON format of extra headers if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='airtime_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airtime_networks', to='subcard_app.apiprovider'),
        ),
        migrations.AddField(
            model_name='network',
            name='data_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_networks', to='subcard_app.apiprovider'),
        ),
    ]
