# Generated by Django 6.0.4 on 2026-05-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcard_app', '0023_apiprovider_network_airtime_api_network_data_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiprovider',
            name='plans_endpoint',
            field=models.CharField(default='/plans', help_text='Endpoint to fetch data plans list', max_length=255),
        ),
    ]
