"""
Django settings for subcard_v12 project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t$wr+b!2(fqrw0vf#$w9zrwh6j7r0^7^rxr=tdw_%*1$(6igiv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['scalping-polio-deface.ngrok-free.dev', '127.0.0.1', 'localhost']
CSRF_TRUSTED_ORIGINS = ['https://scalping-polio-deface.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'subcard_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'subcard_app.middleware.MaintenanceModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'subcard_v12.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'subcard_v12.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

AUTH_USER_MODEL = 'subcard_app.CustomUser'

LOGOUT_REDIRECT_URL = '/'

# SME Plug API Configuration
# Get your API key from https://smeplug.ng/dashboard
SMEPLUG_API_KEY = '900fd38e4873cdf10f501db5ca4bc95c0984f559bf89706ce52513123a6cf6a4'

# Katpay Configuration
# Get your keys from Katpay dashboard
KATPAY_SECRET_KEY = 'eyJpdiI6InM3THFHT0RjbnBHNjN2VkZpaUNhU3c9PSIsInZhbHVlIjoiZHJWOUgyOXcrUHNOK2hoVkI0SUR0cjd3YUJNU3FCelR5VkxDaHBpeGhxdUxGTmg5N2VJbC9wMW5UV1N0ck1URlVKUW53ai9hTmhwRnJPTmVWNjJ0Q3VoYWZYOW4zNWpYSXJEenhqQTU1OFJOVU5pSlhGTDVGR0RWU2FDSmNFZmgiLCJtYWMiOiIxNDgzY2ZkZWYyYmI3NDU3Zjg2Zjg2NDhhMmYzNjllMjNhODZmMTRkMjIzOWIwN2QxZGFmNDM3ZDQ5YjA5NDYzIiwidGFnIjoiIn0='
KATPAY_PUBLIC_KEY = 'pk_live_J7VdLNPR32nqHvxhTNz4t6QmCgOEj1oUIOq5SzNhvOqa18zR3qwp0L1jCGT6E4y4'
KATPAY_MERCHANT_ID = 'KAT7099709161'
KATPAY_BASE_URL = 'https://api.katpay.co/v1/'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yickeytony@gmail.com'
EMAIL_HOST_PASSWORD = 'zzrf nrsy wosg yjuk'
DEFAULT_FROM_EMAIL = 'Subcard <yickeytony@gmail.com>'

# Password reset token timeout (3 hours in seconds)
PASSWORD_RESET_TIMEOUT = 10800
